# Generated by Django 4.2.3 on 2023-07-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_mentor',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
    ]
